### ISSUE TITLE
I like this very much, but why are the events listed outside of the classes?

### ISSUE THREAD

**Issue by clairestreb** [Corcules/corcules-jsdoc#1]
I like this very much, but why are the events listed outside of the classes?

**Comment by Corcules** [comment]
For some decoupled projects, event are drived by html.

Someone write the html like this :
`<button class="btn btn-red action-delete">Delete</button>`

Someone else write the js like this (jquery): 
/**
@event action-delete
**/
`$('.action-delete').on('click', actionDelete );
function actionDelete() {
// delete something
}
`
Goal is to document the js for both person.
